//! Network node — consensus runner + P2P for multi-node operation.
//!
//! Combines:
//! - ConsensusRunner (slot timing, VRF election, block production)
//! - SealNode P2P (GossipSub for block/tx propagation)
//! - Block serialization for network transmission
//!
//! Flow per slot:
//! 1. Advance slot, run VRF election
//! 2. If proposer: produce block → serialize → broadcast via GossipSub
//! 3. If committee: receive block from GossipSub → verify → vote
//! 4. Collect threshold votes → finalize

use seal_consensus::config::ConsensusConfig;
use seal_consensus::validator::ValidatorSet;
use seal_crypto::hash::Hash256;
use seal_crypto::signature::SigningKey;
use seal_p2p::node::{BridgeRingtailBroadcaster, NetworkMessage, NodeConfig, SealNode};
use seal_storage::block_store::{Block, Transaction};
use seal_vrf::traits::Vrf;

use crate::consensus_runner::{ConsensusRunner, FinalizedBlock};

use std::sync::Arc;
use tokio::sync::mpsc;
use tokio::sync::Mutex as TokioMutex;
use tracing::{debug, error, info, warn};

/// A network-connected Seal node.
pub struct NetworkNode {
    /// Consensus runner.
    pub runner: ConsensusRunner,
    /// P2P node.
    p2p: SealNode,
    /// Our peer ID.
    pub peer_id: libp2p::PeerId,
    /// Blocks received from the network (not yet processed).
    received_blocks: Vec<Block>,
    /// Rate limiting: messages processed per tick.
    max_messages_per_tick: usize,
    /// Rate limiting: maximum received block queue size.
    max_received_blocks: usize,
    /// Shared bridge manager (P1#5 layer 4). `Some` after
    /// `attach_bridge` is called from seal-node main; the receive
    /// loop uses it to call `attach_committee_signature` on the
    /// Round2Complete + race-loser Aggregate paths.
    bridge: Option<Arc<TokioMutex<seal_bridge::BridgeManager>>>,
    /// Shared multi-validator Ringtail signing orchestrator
    /// (P1#5 layer 4 / ADR-002). `Some` when the operator opted in
    /// AND the `ringtail-singleton` feature is on; the receive loop
    /// pumps Round1/Round2/Aggregate envelopes through it.
    #[cfg(feature = "ringtail-singleton")]
    ringtail_orchestrator:
        Option<Arc<TokioMutex<seal_bridge::ringtail_orchestrator::RingtailBridgeOrchestrator>>>,
    /// On-disk store for in-flight Ringtail signing sessions (§3 of
    /// the no-excuse-bordel plan — restart-resume). When attached,
    /// the receive loop persists a fresh snapshot after every
    /// successful ingest_round*_envelope and deletes the file once
    /// the session completes + drops. `None` keeps the in-memory-
    /// only behaviour (peers re-broadcast on restart, protocol
    /// resumes from scratch).
    #[cfg(feature = "ringtail-singleton")]
    ringtail_session_store: Option<Arc<seal_bridge::ringtail_store::RingtailSessionStore>>,
}

impl NetworkNode {
    /// Start a network node with a fresh ML-DSA identity. For
    /// stable on-chain identity across restarts use
    /// [`Self::start_with_keypair`].
    pub async fn start(
        consensus_config: ConsensusConfig,
        p2p_config: NodeConfig,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let (p2p, peer_id) = SealNode::start(p2p_config).await?;
        let runner = ConsensusRunner::new(consensus_config);

        info!(%peer_id, "Network node started");

        Ok(NetworkNode {
            runner,
            p2p,
            peer_id,
            received_blocks: Vec::new(),
            max_messages_per_tick: 100,
            max_received_blocks: 1000,
            bridge: None,
            #[cfg(feature = "ringtail-singleton")]
            ringtail_orchestrator: None,
            #[cfg(feature = "ringtail-singleton")]
            ringtail_session_store: None,
        })
    }

    /// Start a network node using a caller-supplied validator
    /// identity (the on-chain ML-DSA keypair). Drives the
    /// `seal-node --validator-key <path>` flag: the same keyfile
    /// across restarts yields the same address, VRF state, and
    /// signing keys, so testnet operators don't have to re-register
    /// or re-stake after a reboot.
    ///
    /// libp2p still derives its peer ID from a separate transport
    /// keypair generated by `SealNode::start`; the validator's
    /// on-chain identity is what this argument pins.
    pub async fn start_with_keypair(
        consensus_config: ConsensusConfig,
        p2p_config: NodeConfig,
        signing_key: SigningKey,
        verifying_key: seal_crypto::signature::VerifyingKey,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let (p2p, peer_id) = SealNode::start(p2p_config).await?;
        let runner =
            ConsensusRunner::new_with_keypair(consensus_config, signing_key, verifying_key);

        info!(%peer_id, "Network node started with persistent validator identity");

        Ok(NetworkNode {
            runner,
            p2p,
            peer_id,
            received_blocks: Vec::new(),
            max_messages_per_tick: 100,
            max_received_blocks: 1000,
            bridge: None,
            #[cfg(feature = "ringtail-singleton")]
            ringtail_orchestrator: None,
            #[cfg(feature = "ringtail-singleton")]
            ringtail_session_store: None,
        })
    }

    /// Start with a specific validator set (for multi-node testing).
    pub async fn start_with_validators(
        consensus_config: ConsensusConfig,
        p2p_config: NodeConfig,
        signing_key: SigningKey,
        verifying_key: seal_crypto::signature::VerifyingKey,
        vrf_manager: seal_vrf::VrfKeyManager,
        validator_set: ValidatorSet,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let (p2p, peer_id) = SealNode::start(p2p_config).await?;
        let runner = ConsensusRunner::with_validator_set(
            consensus_config,
            signing_key,
            verifying_key,
            vrf_manager,
            validator_set,
        )?;

        info!(%peer_id, "Network node started with validator set");

        Ok(NetworkNode {
            runner,
            p2p,
            peer_id,
            received_blocks: Vec::new(),
            max_messages_per_tick: 100,
            max_received_blocks: 1000,
            bridge: None,
            #[cfg(feature = "ringtail-singleton")]
            ringtail_orchestrator: None,
            #[cfg(feature = "ringtail-singleton")]
            ringtail_session_store: None,
        })
    }

    /// Process one slot: check for network messages, then advance consensus.
    /// Returns a finalized block if one was produced this slot.
    pub async fn tick(&mut self) -> Option<FinalizedBlock> {
        // 1. Drain incoming network messages
        self.process_network_messages().await;

        // 2. Auto-apply received blocks from peers
        self.apply_received_blocks();

        // 3. Advance consensus slot
        let block = self.runner.advance_slot();

        // 3b. If this slot crossed an epoch boundary, broadcast the
        // signed transition announcement (audit B.8: peers verify
        // signature + seed derivation before applying it).
        if let Some(transition) = self.runner.take_pending_epoch_transition() {
            match bincode::serialize(&transition) {
                Ok(data) => {
                    if let Err(e) = self.p2p.broadcast_epoch_transition(data).await {
                        warn!("Failed to broadcast epoch transition: {}", e);
                    }
                }
                Err(e) => {
                    error!("Failed to serialize epoch transition: {}", e);
                }
            }
        }

        // 4. If we produced a block, broadcast it
        if let Some(ref finalized) = block {
            self.broadcast_block(&finalized.block).await;
        }

        block
    }

    /// Apply all received blocks that are at the next expected height.
    /// Skips blocks that are too old or too far ahead.
    fn apply_received_blocks(&mut self) {
        if self.received_blocks.is_empty() {
            return;
        }

        // Sort by height to apply in order
        self.received_blocks.sort_by_key(|b| b.header.height);

        let mut applied = 0;
        let mut remaining = Vec::new();

        for block in std::mem::take(&mut self.received_blocks) {
            let expected = self.runner.height() + 1;
            if block.header.height == expected {
                match self.verify_and_apply_block(&block) {
                    Ok(()) => {
                        applied += 1;
                    }
                    Err(e) => {
                        debug!(
                            height = block.header.height,
                            error = %e,
                            "Failed to apply received block"
                        );
                    }
                }
            } else if block.header.height > expected {
                // Future block — keep for later
                remaining.push(block);
            }
            // else: old block — discard
        }

        self.received_blocks = remaining;

        if applied > 0 {
            info!(applied, "Applied received blocks from peers");
        }
    }

    /// Process pending network messages (non-blocking, rate-limited).
    async fn process_network_messages(&mut self) {
        let mut processed = 0;
        loop {
            if processed >= self.max_messages_per_tick {
                debug!("Rate limit: {} messages processed this tick", processed);
                break;
            }
            match self.p2p.receiver.try_recv() {
                Ok(msg) => {
                    processed += 1;
                    match msg {
                        NetworkMessage::NewBlock { data, source } => {
                            // Drop if queue is full (backpressure)
                            if self.received_blocks.len() >= self.max_received_blocks {
                                warn!("Block queue full, dropping block from {}", source);
                                continue;
                            }
                            match bincode::deserialize::<Block>(&data) {
                                Ok(block) => {
                                    debug!(
                                        height = block.header.height,
                                        from = %source,
                                        "Received block from network"
                                    );
                                    self.received_blocks.push(block);
                                }
                                Err(e) => {
                                    warn!("Failed to deserialize block: {}", e);
                                }
                            }
                        }
                        NetworkMessage::NewTransaction { data, source } => {
                            match bincode::deserialize::<Transaction>(&data) {
                                Ok(tx) => {
                                    debug!(
                                        tx_type = ?tx.tx_type,
                                        from = %source,
                                        "Received tx from network"
                                    );
                                    if let Err(e) = self.runner.accept_transaction(tx) {
                                        debug!("Rejected tx from {}: {}", source, e);
                                    }
                                }
                                Err(e) => {
                                    warn!("Failed to deserialize tx from {}: {}", source, e);
                                }
                            }
                        }
                        NetworkMessage::CommitteeVote { data, source } => {
                            debug!(from = %source, bytes = data.len(), "Received committee vote");
                            if let Err(e) = self.runner.accept_committee_vote(&data) {
                                warn!("Rejected committee vote from {}: {}", source, e);
                            }
                        }
                        NetworkMessage::CommitteeSignature { data, source } => {
                            debug!(from = %source, bytes = data.len(), "Received committee signature");
                            if let Err(e) = self.runner.accept_committee_signature(&data) {
                                warn!("Rejected committee signature from {}: {}", source, e);
                            }
                        }
                        NetworkMessage::EpochTransition { data, source } => {
                            debug!(from = %source, bytes = data.len(), "Received epoch transition");
                            if let Err(e) = self.runner.accept_epoch_transition(&data) {
                                warn!("Rejected epoch transition from {}: {}", source, e);
                            }
                        }
                        // P1#5 layer 4 — bridge multi-validator
                        // Ringtail signing. Each envelope is routed
                        // through the local orchestrator; on each
                        // protocol-event return (Round2 envelope ready,
                        // aggregate signature ready) we (a) re-broadcast
                        // the returned envelope so peers converge and
                        // (b) on Round2Complete / aggregate, attach the
                        // final signature to the local BridgeManager
                        // so seal_bridgeWithdraw queries see it.
                        //
                        // The default (no orchestrator attached) keeps
                        // the debug-log-and-drop behaviour so HMAC
                        // committee-of-1 nodes pay no extra cost.
                        NetworkMessage::BridgeRingtailRound1 { data, source } => {
                            self.handle_bridge_ringtail_round1(data, source).await;
                        }
                        NetworkMessage::BridgeRingtailRound2 { data, source } => {
                            self.handle_bridge_ringtail_round2(data, source).await;
                        }
                        NetworkMessage::BridgeRingtailAggregate { data, source } => {
                            self.handle_bridge_ringtail_aggregate(data, source).await;
                        }
                        NetworkMessage::PeerConnected(peer) => {
                            info!(%peer, "Peer connected");
                        }
                        NetworkMessage::PeerDisconnected(peer) => {
                            debug!(%peer, "Peer disconnected");
                        }
                    }
                }
                Err(mpsc::error::TryRecvError::Empty) => break,
                Err(mpsc::error::TryRecvError::Disconnected) => {
                    warn!("P2P channel disconnected");
                    break;
                }
            }
        }
    }

    /// Broadcast a block to all connected peers.
    async fn broadcast_block(&self, block: &Block) {
        match bincode::serialize(block) {
            Ok(data) => {
                info!(
                    height = block.header.height,
                    bytes = data.len(),
                    "Broadcasting block"
                );
                if let Err(e) = self.p2p.broadcast_block(data).await {
                    warn!("Failed to broadcast block: {}", e);
                }
            }
            Err(e) => {
                warn!("Failed to serialize block: {}", e);
            }
        }
    }

    /// Broadcast a transaction to all connected peers.
    pub async fn broadcast_transaction(&self, tx: &Transaction) {
        match bincode::serialize(tx) {
            Ok(data) => {
                debug!(
                    tx_type = ?tx.tx_type,
                    bytes = data.len(),
                    "Broadcasting transaction"
                );
                if let Err(e) = self.p2p.broadcast_transaction(data).await {
                    warn!("Failed to broadcast tx: {}", e);
                }
            }
            Err(e) => {
                warn!("Failed to serialize tx: {}", e);
            }
        }
    }

    /// Cloneable handle to the three bridge-Ringtail broadcast
    /// topics. Lets the seal-node start_signing task + the receive
    /// loop drive broadcasts without holding a guard over
    /// `NetworkNode` (which is `!Sync` and would therefore fail
    /// `tokio::spawn`'s `Send` bound when held across an await).
    pub fn ringtail_broadcaster(&self) -> BridgeRingtailBroadcaster {
        self.p2p.ringtail_broadcaster()
    }

    /// Attach the shared `BridgeManager` (P1#5 layer 4 ADR-002). The
    /// network event loop calls `attach_committee_signature` on the
    /// Round2Complete + race-loser-Aggregate paths so a final
    /// signature lands on every validator's BridgeManager, not just
    /// the one that aggregated locally. Must be called from seal-node
    /// main before `tick()` is driven; calling it twice replaces the
    /// previously-attached handle (last-writer-wins).
    pub fn attach_bridge(&mut self, bridge: Arc<TokioMutex<seal_bridge::BridgeManager>>) {
        self.bridge = Some(bridge);
    }

    /// Attach the shared multi-validator Ringtail orchestrator. The
    /// network event loop pumps every incoming
    /// `BridgeRingtail{Round1,Round2,Aggregate}` envelope through it
    /// and broadcasts any envelope the orchestrator returns. Must be
    /// called from seal-node main before `tick()` is driven.
    #[cfg(feature = "ringtail-singleton")]
    pub fn attach_ringtail_orchestrator(
        &mut self,
        orch: Arc<TokioMutex<seal_bridge::ringtail_orchestrator::RingtailBridgeOrchestrator>>,
    ) {
        self.ringtail_orchestrator = Some(orch);
    }

    /// Attach an on-disk store for Ringtail signing sessions. The
    /// receive loop persists a snapshot after every successful
    /// envelope ingest so a node restart can resume from where it
    /// left off. Pairs with the orchestrator's
    /// `export_session` / `restore_session` API and the
    /// `ringtail_session_store::RingtailSessionStore` disk format.
    /// §3 of the no-excuse-bordel plan.
    #[cfg(feature = "ringtail-singleton")]
    pub fn attach_ringtail_session_store(
        &mut self,
        store: Arc<seal_bridge::ringtail_store::RingtailSessionStore>,
    ) {
        self.ringtail_session_store = Some(store);
    }

    /// Handle one incoming `BridgeRingtailRound1` envelope (P1#5
    /// layer 4 — ADR-002 routing). Drops with a debug log when no
    /// orchestrator is attached (HMAC committee-of-1 default path).
    /// On a successful Round1Complete event, the orchestrator returns
    /// a Round2 envelope which we re-broadcast so peers can ingest it.
    async fn handle_bridge_ringtail_round1(&self, data: Vec<u8>, source: libp2p::PeerId) {
        debug!(from = %source, bytes = data.len(), "Received bridge-ringtail round1");
        #[cfg(feature = "ringtail-singleton")]
        {
            let Some(orch) = self.ringtail_orchestrator.as_ref() else {
                return;
            };
            let env: seal_bridge::ringtail::BridgeRingtailRound1Envelope =
                match serde_json::from_slice(&data) {
                    Ok(e) => e,
                    Err(e) => {
                        warn!(from = %source, error = %e, "deserialize bridge-ringtail round1");
                        return;
                    }
                };
            let wd_id = env.withdrawal_id.clone();
            let (round2_env, snap) = {
                let mut o = orch.lock().await;
                let r2 = match o.on_round1_envelope(env) {
                    Ok(Some(e)) => Some(e),
                    Ok(None) => None,
                    Err(e) => {
                        warn!(from = %source, wd_id = %wd_id, error = %e, "round1 ingest rejected");
                        return;
                    }
                };
                let snap = o.export_session(&wd_id);
                (r2, snap)
            };
            self.persist_session_snapshot(&wd_id, snap);
            if let Some(env2) = round2_env {
                match serde_json::to_vec(&env2) {
                    Ok(bytes) => {
                        if let Err(e) = self.p2p.broadcast_bridge_ringtail_round2(bytes).await {
                            warn!(wd_id = %wd_id, error = %e, "broadcast bridge-ringtail round2");
                        }
                    }
                    Err(e) => {
                        warn!(wd_id = %wd_id, error = %e, "serialize bridge-ringtail round2");
                    }
                }
            }
        }
        #[cfg(not(feature = "ringtail-singleton"))]
        {
            let _ = data;
        }
    }

    /// Handle one incoming `BridgeRingtailRound2` envelope. On
    /// Round2Complete the orchestrator returns the aggregate
    /// envelope: we re-broadcast it, attach it to the local
    /// BridgeManager, and drop the orchestrator session.
    async fn handle_bridge_ringtail_round2(&self, data: Vec<u8>, source: libp2p::PeerId) {
        debug!(from = %source, bytes = data.len(), "Received bridge-ringtail round2");
        #[cfg(feature = "ringtail-singleton")]
        {
            let Some(orch) = self.ringtail_orchestrator.as_ref() else {
                return;
            };
            let env: seal_bridge::ringtail::BridgeRingtailRound2Envelope =
                match serde_json::from_slice(&data) {
                    Ok(e) => e,
                    Err(e) => {
                        warn!(from = %source, error = %e, "deserialize bridge-ringtail round2");
                        return;
                    }
                };
            let wd_id = env.withdrawal_id.clone();
            let (agg_env, snap_after_ingest) = {
                let mut o = orch.lock().await;
                let agg = match o.on_round2_envelope(env) {
                    Ok(Some(e)) => Some(e),
                    Ok(None) => None,
                    Err(e) => {
                        warn!(from = %source, wd_id = %wd_id, error = %e, "round2 ingest rejected");
                        return;
                    }
                };
                let snap = o.export_session(&wd_id);
                (agg, snap)
            };
            // Persist whatever we just ingested, even if Round2
            // hasn't completed yet — a restart between this Round2
            // and the matching `drop_session` would otherwise lose
            // progress.
            self.persist_session_snapshot(&wd_id, snap_after_ingest);
            if let Some(agg) = agg_env {
                // Attach to local BridgeManager FIRST so a partial
                // broadcast failure still leaves the local node with
                // a signed withdrawal record. Then drop the
                // orchestrator session so the in-memory queue doesn't
                // grow without bound.
                if let Some(bridge) = self.bridge.as_ref() {
                    if let Err(e) = bridge
                        .lock()
                        .await
                        .attach_committee_signature(&wd_id, agg.signature_hex.clone())
                    {
                        warn!(wd_id = %wd_id, error = ?e, "attach_committee_signature");
                    }
                }
                orch.lock().await.drop_session(&wd_id);
                self.delete_session_snapshot(&wd_id);
                match serde_json::to_vec(&agg) {
                    Ok(bytes) => {
                        if let Err(e) = self.p2p.broadcast_bridge_ringtail_aggregate(bytes).await {
                            warn!(wd_id = %wd_id, error = %e, "broadcast bridge-ringtail aggregate");
                        }
                    }
                    Err(e) => {
                        warn!(wd_id = %wd_id, error = %e, "serialize bridge-ringtail aggregate");
                    }
                }
            }
        }
        #[cfg(not(feature = "ringtail-singleton"))]
        {
            let _ = data;
        }
    }

    /// Handle one incoming `BridgeRingtailAggregate` envelope. This
    /// is the race-loser path: a peer reached the aggregate before
    /// the local validator did. Attach the supplied signature_hex to
    /// the local BridgeManager + drop the in-flight orchestrator
    /// session if present.
    async fn handle_bridge_ringtail_aggregate(&self, data: Vec<u8>, source: libp2p::PeerId) {
        debug!(from = %source, bytes = data.len(), "Received bridge-ringtail aggregate");
        #[cfg(feature = "ringtail-singleton")]
        {
            let env: seal_bridge::ringtail::BridgeRingtailAggregateEnvelope =
                match serde_json::from_slice(&data) {
                    Ok(e) => e,
                    Err(e) => {
                        warn!(from = %source, error = %e, "deserialize bridge-ringtail aggregate");
                        return;
                    }
                };
            if let Some(bridge) = self.bridge.as_ref() {
                if let Err(e) = bridge
                    .lock()
                    .await
                    .attach_committee_signature(&env.withdrawal_id, env.signature_hex.clone())
                {
                    warn!(wd_id = %env.withdrawal_id, error = ?e, "attach_committee_signature (race-loser)");
                }
            }
            if let Some(orch) = self.ringtail_orchestrator.as_ref() {
                orch.lock().await.drop_session(&env.withdrawal_id);
                self.delete_session_snapshot(&env.withdrawal_id);
            }
        }
        #[cfg(not(feature = "ringtail-singleton"))]
        {
            let _ = data;
        }
    }

    /// Persist a snapshot of one signing session to disk if the
    /// store is attached. No-op when persistence is off OR when the
    /// caller's `export_session` returned `None` (unknown wd_id).
    #[cfg(feature = "ringtail-singleton")]
    fn persist_session_snapshot(
        &self,
        wd_id: &str,
        snap: Option<seal_bridge::ringtail_orchestrator::InFlightSnapshot>,
    ) {
        let (Some(store), Some(snap)) = (self.ringtail_session_store.as_ref(), snap) else {
            return;
        };
        if let Err(e) = store.save(&snap) {
            warn!(wd_id = %wd_id, error = %e, "persist ringtail session snapshot");
        }
    }

    /// Delete a persisted session — called from the receive loop
    /// after a successful aggregate attaches + drop_session lands.
    #[cfg(feature = "ringtail-singleton")]
    fn delete_session_snapshot(&self, wd_id: &str) {
        let Some(store) = self.ringtail_session_store.as_ref() else {
            return;
        };
        if let Err(e) = store.delete(wd_id) {
            warn!(wd_id = %wd_id, error = %e, "delete ringtail session snapshot");
        }
    }

    /// Submit a SQL transaction.
    pub fn submit_sql(
        &mut self,
        sql: &str,
    ) -> Result<seal_sql::engine::QueryResult, seal_sql::SqlError> {
        self.runner.submit_sql(sql)
    }

    /// Query SQL (read-only).
    pub fn query_sql(
        &mut self,
        sql: &str,
    ) -> Result<seal_sql::engine::QueryResult, seal_sql::SqlError> {
        self.runner.query_sql(sql)
    }

    /// Get chain height.
    pub fn height(&self) -> u64 {
        self.runner.height()
    }

    /// Get state root.
    pub fn state_root(&self) -> &Hash256 {
        self.runner.state_root()
    }

    /// Get number of blocks received from the network.
    pub fn received_block_count(&self) -> usize {
        self.received_blocks.len()
    }

    /// Run the consensus loop with real slot timing.
    /// Ticks every `slot_duration` (default 4s), producing blocks when elected.
    /// Runs for `max_slots` slots then returns.
    pub async fn run_consensus(&mut self, max_slots: u64) {
        let slot_duration = self.runner.config.slot_duration;
        let mut interval = tokio::time::interval(slot_duration);

        for slot in 0..max_slots {
            interval.tick().await;

            if let Some(block) = self.tick().await {
                info!(
                    slot,
                    height = block.block.header.height,
                    txs = block.block.transactions.len(),
                    "Block finalized"
                );
            }
        }
    }

    /// Take received blocks (for processing).
    pub fn take_received_blocks(&mut self) -> Vec<Block> {
        std::mem::take(&mut self.received_blocks)
    }

    /// Verify and apply a received block.
    /// Checks:
    /// 1. Height is sequential (next expected height)
    /// 2. Parent hash matches our latest block
    /// 3. Proposer signature is valid (ML-DSA over the empty-sig header
    ///    serialization, verified against `header.proposer`)
    /// 4. VRF proof is valid (proposer was legitimately elected)
    /// 5. Replaying transactions produces the claimed state root
    pub fn verify_and_apply_block(&mut self, block: &Block) -> Result<(), String> {
        let expected_height = self.runner.height() + 1;
        if block.header.height != expected_height {
            return Err(format!(
                "unexpected height: expected {}, got {}",
                expected_height, block.header.height
            ));
        }

        // Check parent hash
        if self.runner.height() > 0 {
            let our_latest = self.runner.latest_block().ok_or("no latest block")?;
            let our_header_bytes = bincode::serialize(&our_latest.block.header)
                .map_err(|e| format!("serialize error: {}", e))?;
            let expected_parent = seal_crypto::hash::sha3_256(&our_header_bytes);
            if block.header.parent_hash != expected_parent {
                return Err("parent hash mismatch".into());
            }
        }

        // Bind the transaction set to the signed header. Without this, a
        // relayer could inject, remove, or modify a no-op transaction
        // (DexMatch, token/bridge/stake) in a validly-signed block and every
        // node would commit it: no-op txs affect neither `state_root` (the F2
        // root check) nor the header signature, so neither would catch them.
        // Recomputing the Merkle root from the received transactions and
        // comparing it to the signed `header.tx_root` closes that gap for
        // every transaction type (design:
        // audits/2026-10-08-dexmatch-txroot-design.md).
        let recomputed_tx_root =
            seal_storage::block_store::transactions_root(&block.transactions);
        if recomputed_tx_root != block.header.tx_root {
            return Err(
                "transaction root mismatch: block transactions were modified after signing"
                    .into(),
            );
        }

        // Verify the proposer's ML-DSA signature over the canonical
        // (empty-sig) header serialization. A block without a signature
        // cannot be attributed to a real key holder and is rejected.
        if block.header.proposer_signature.is_empty() {
            return Err("block is missing the proposer signature".into());
        }
        let proposer_vk = seal_crypto::signature::VerifyingKey::from_bytes(
            &block.header.proposer,
        )
        .map_err(|e| format!("invalid proposer key: {}", e))?;
        let mut unsigned_header = block.header.clone();
        unsigned_header.proposer_signature.clear();
        let sign_bytes = bincode::serialize(&unsigned_header)
            .map_err(|e| format!("serialize error: {}", e))?;
        let sig = seal_crypto::signature::Signature::from_bytes(
            block.header.proposer_signature.clone(),
        );
        proposer_vk
            .verify(&sign_bytes, &sig)
            .map_err(|e| format!("proposer signature verification failed: {}", e))?;

        // The proposer must be a registered validator. The signature above
        // only proves the block came from SOME key holder; it is verified
        // against `header.proposer`, a key the proposer names in the header
        // itself, so a forger can name their own key and sign the header.
        // Binding the proposer to the validator set is what stops an
        // arbitrary key holder from gossipping a self-signed block with
        // empty VRF fields (which skips the election check below) and moving
        // funds out of any account. Without this, any peer could fabricate a
        // validly-signed block debiting a funded account and every node would
        // apply it (audit finding F1).
        //
        // The check fires only on a node *enrolled* in an explicit validator
        // set. A node that booted with the isolated single-validator set
        // (`new` / `new_with_keypair`) has no shared set to check against —
        // it is single-validator local dev, where there are no peer proposers
        // to forge — so it keeps the legacy self-attested behaviour and does
        // not start rejecting every block from another isolated node. Full
        // F1 protection requires every peer in a network to be enrolled in
        // the same validator set (validator-set bootstrap, a follow-up).
        if self.runner.enrolled && self
            .runner
            .validator_set
            .find_by_pubkey(&block.header.proposer)
            .is_none()
        {
            return Err("block proposer is not a registered validator".into());
        }

        // Verify VRF proof if present (proves proposer was legitimately elected)
        if !block.header.vrf_output.is_empty() && !block.header.vrf_proof.is_empty() {
            // Find the proposer in our validator set
            if let Some(proposer) = self
                .runner
                .validator_set
                .find_by_pubkey(&block.header.proposer)
            {
                let vrf_input = self
                    .runner
                    .current_slot
                    .vrf_input(&self.runner.current_epoch.seed);
                let vrf_output = seal_vrf::VrfOutput(
                    block
                        .header
                        .vrf_output
                        .as_slice()
                        .try_into()
                        .map_err(|_| "invalid VRF output length")?,
                );
                let vrf_proof = seal_vrf::VrfProof {
                    bytes: block.header.vrf_proof.clone(),
                };
                // Verify using PqVrf (the proposer's VRF public key)
                seal_vrf::PqVrf::verify(
                    &proposer.vrf_public_key,
                    &vrf_input,
                    &vrf_output,
                    &vrf_proof,
                )
                .map_err(|e| format!("VRF proof verification failed: {}", e))?;

                debug!(height = block.header.height, "VRF proof verified");
            }
            // If proposer not in our validator set, skip VRF check (they may have rotated)
        }

        // Verify the replayed state root BEFORE committing the block, and drop
        // the finalized txs from the pending pool (audits F2 + F5). A root
        // mismatch or a transition error rolls the node back to its pre-replay
        // state, so a forged/modified block cannot advance the height or mutate
        // the ledger.
        self.runner
            .apply_block_verified(block)
            .map_err(|e| format!("replay/verify failed: {}", e))?;

        info!(
            height = block.header.height,
            state_root = %block.header.state_root,
            "Block verified and applied"
        );

        Ok(())
    }

    /// Sync with another node by applying its blocks.
    /// Requests blocks from `from_height` to `to_height` inclusive.
    /// In production: these blocks would come over P2P. For now, takes a slice.
    pub fn sync_blocks(&mut self, blocks: &[Block]) -> Result<u64, String> {
        let mut applied = 0;
        for block in blocks {
            // Skip blocks we already have
            if block.header.height <= self.runner.height() {
                continue;
            }
            // Verify and apply
            self.verify_and_apply_block(block)?;
            applied += 1;
        }
        Ok(applied)
    }

    /// Get all blocks this node has produced (for sharing with peers).
    pub fn get_chain(&self) -> Vec<Block> {
        self.runner
            .chain
            .iter()
            .map(|fb| fb.block.clone())
            .collect()
    }

    /// Check if this node is behind another node's height.
    pub fn is_behind(&self, remote_height: u64) -> bool {
        self.runner.height() < remote_height
    }

    /// How many blocks behind are we?
    pub fn blocks_behind(&self, remote_height: u64) -> u64 {
        remote_height.saturating_sub(self.runner.height())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_network_node_starts() {
        let node = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();

        assert!(!node.peer_id.to_string().is_empty());
        assert_eq!(node.height(), 0);
        assert_eq!(node.received_block_count(), 0);
    }

    #[tokio::test]
    async fn test_network_node_produces_blocks() {
        let mut node = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();

        node.submit_sql("CREATE TABLE t (id BIGINT PRIMARY KEY)")
            .unwrap();

        let mut produced = false;
        for _ in 0..100 {
            if node.tick().await.is_some() {
                produced = true;
                break;
            }
        }
        assert!(produced, "should produce at least one block");
        assert!(node.height() > 0);
    }

    #[tokio::test]
    async fn test_network_node_sql() {
        let mut node = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();

        node.submit_sql("CREATE TABLE users (id BIGINT PRIMARY KEY, name TEXT NOT NULL)")
            .unwrap();
        node.submit_sql("INSERT INTO users (id, name) VALUES (1, 'alice')")
            .unwrap();

        let result = node.query_sql("SELECT * FROM users").unwrap();
        assert_eq!(result.rows.len(), 1);
    }

    #[tokio::test]
    async fn test_block_serialization_roundtrip() {
        // Verify blocks can be serialized and deserialized for network transmission
        let mut node = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();

        node.submit_sql("CREATE TABLE t (id BIGINT PRIMARY KEY, val TEXT)")
            .unwrap();
        node.submit_sql("INSERT INTO t (id, val) VALUES (1, 'test')")
            .unwrap();

        let mut block = None;
        for _ in 0..100 {
            if let Some(b) = node.tick().await {
                block = Some(b);
                break;
            }
        }
        let block = block.unwrap();

        // Serialize and deserialize
        let bytes = bincode::serialize(&block.block).unwrap();
        let deserialized: Block = bincode::deserialize(&bytes).unwrap();

        assert_eq!(deserialized.header.height, block.block.header.height);
        assert_eq!(
            deserialized.header.state_root,
            block.block.header.state_root
        );
        assert_eq!(
            deserialized.transactions.len(),
            block.block.transactions.len()
        );
    }

    /// Two *enrolled* nodes sharing a two-validator set: node A (the
    /// producer) is active, node B (the receiver) is inactive.
    ///
    /// Both nodes are built via `start_with_validators`, so each is
    /// *enrolled* and the proposer-membership check in
    /// `verify_and_apply_block` is live on both. The receiver therefore
    /// only accepts blocks from a registered validator — exactly the
    /// behaviour the tests exercise.
    ///
    /// The producer is the only *active* validator, so on its side
    /// `active_count() == 1` and it produces a block on **every** slot
    /// (the `Committee` fallback in `advance_slot`), making the tests
    /// deterministic. The receiver is inactive so that ticking it — to
    /// keep its slot in step with the producer — never makes it produce a
    /// block of its own: the VRF check in `verify_and_apply_block`
    /// verifies a block against the *verifier's own* current slot, so the
    /// receiver must be at the same slot the block was proposed in.
    ///
    /// Both entries carry their REAL VRF public key (captured before the
    /// key managers are moved into the nodes): the receiver verifies the
    /// producer's election proof against the `vrf_public_key` recorded here.
    async fn start_validator_pair() -> (NetworkNode, NetworkNode) {
        use seal_consensus::validator::ValidatorInfo;
        use seal_crypto::hash::sha3_256;
        use seal_vrf::VrfKeyManager;

        let (sk_a, vk_a) = SigningKey::generate();
        let (sk_b, vk_b) = SigningKey::generate();
        let vrf_a = VrfKeyManager::new(sha3_256(b"test_node_a").0);
        let vrf_b = VrfKeyManager::new(sha3_256(b"test_node_b").0);
        // Real epoch-0 public keys. Tests stay within epoch 0, so these are
        // the keys the election proofs are generated (and verified) with.
        let vrf_a_pk = vrf_a.public_key().to_vec();
        let vrf_b_pk = vrf_b.public_key().to_vec();

        let set = ValidatorSet::new(vec![
            ValidatorInfo {
                public_key: vk_a.to_bytes(),
                vrf_public_key: vrf_a_pk,
                stake: 1_000_000_000,
                active: true,
            },
            ValidatorInfo {
                public_key: vk_b.to_bytes(),
                vrf_public_key: vrf_b_pk,
                stake: 1_000_000_000,
                // Inactive so the receiver never produces on its own while
                // we tick it to stay slot-synced with the producer.
                active: false,
            },
        ]);
        let a = NetworkNode::start_with_validators(
            ConsensusConfig::default(),
            NodeConfig::default(),
            sk_a,
            vk_a,
            vrf_a,
            set.clone(),
        )
        .await
        .unwrap();
        let b = NetworkNode::start_with_validators(
            ConsensusConfig::default(),
            NodeConfig::default(),
            sk_b,
            vk_b,
            vrf_b,
            set,
        )
        .await
        .unwrap();
        (a, b)
    }

    /// Apply `chain` to `node` the way the live receive path does: step the
    /// node forward one slot at a time until it reaches each block's
    /// proposal slot, then verify + apply that block.
    ///
    /// `verify_and_apply_block` checks a block's VRF proof against the
    /// *verifier's own* current slot, so a node catching up on historical
    /// blocks must advance its slot to each block's slot first. (The batch
    /// `sync_blocks` helper cannot do that — it applies a whole slice at one
    /// fixed slot, which the current-slot VRF check rejects for older
    /// blocks; storing the proposal slot in the header so catch-up verifies
    /// correctly is a follow-up.) In these tests the producer is the only
    /// active validator, so it produces every slot and block height ==
    /// proposal slot. Returns the number of blocks applied.
    async fn apply_chain_live(node: &mut NetworkNode, chain: &[Block]) -> usize {
        let mut node_slot = node.runner.current_slot.number;
        let mut applied = 0usize;
        for block in chain {
            let target = block.header.height;
            while node_slot < target {
                node.tick().await;
                node_slot += 1;
            }
            if node.verify_and_apply_block(block).is_ok() {
                applied += 1;
            }
        }
        applied
    }

    #[tokio::test]
    async fn test_verify_and_apply_block() {
        // Producer + receiver share an enrolled two-validator set so the
        // receiver recognizes the producer as a registered proposer.
        let (mut producer, mut receiver) = start_validator_pair().await;

        producer
            .submit_sql("CREATE TABLE t (id BIGINT PRIMARY KEY, val TEXT)")
            .unwrap();
        producer
            .submit_sql("INSERT INTO t (id, val) VALUES (1, 'hello')")
            .unwrap();

        // Produce a block, ticking the receiver in lockstep so it stays at
        // the same slot the producer proposes in (the VRF check verifies
        // against the receiver's own current slot).
        let mut block = None;
        for _ in 0..100 {
            receiver.tick().await;
            if let Some(b) = producer.tick().await {
                block = Some(b);
                break;
            }
        }
        let block = block.expect("should produce a block");

        // Receiver node verifies and applies the block
        receiver.verify_and_apply_block(&block.block).unwrap();
        assert_eq!(receiver.height(), 1);

        // Data should be queryable after applying the block
        let result = receiver.query_sql("SELECT * FROM t").unwrap();
        assert_eq!(result.rows.len(), 1);
    }

    /// A block whose proposer is not in the receiver's validator set must be
    /// rejected, even though it is a well-formed, correctly-signed block. This
    /// is the anti-forgery gate: without it any key holder could name
    /// themselves as `proposer`, sign the header, and move arbitrary funds.
    #[tokio::test]
    async fn test_verify_rejects_unknown_proposer() {
        // `producer` has its own isolated single-validator set, so its key is
        // not in the receiver's shared set.
        let mut producer = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();
        let block = produce_one_block(&mut producer).await;
        assert!(!block.header.proposer.is_empty());

        let (mut receiver, _other) = start_validator_pair().await;
        let result = receiver.verify_and_apply_block(&block);
        assert!(
            result.is_err(),
            "block from a proposer outside the validator set must be rejected"
        );
        // Nothing was applied.
        assert_eq!(receiver.height(), 0);
    }

    #[tokio::test]
    async fn test_verify_rejects_wrong_height() {
        let mut node = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();

        // Create a block claiming height 5 (but we're at height 0)
        let block = Block {
            header: seal_storage::block_store::BlockHeader {
                height: 5,
                parent_hash: Hash256::ZERO,
                state_root: Hash256::ZERO,
                timestamp: 0,
                proposer: vec![],
                vrf_output: vec![],
                vrf_proof: vec![],
                proposer_signature: vec![],
                tx_root: Hash256::ZERO,
            },
            transactions: vec![],
        };

        let result = node.verify_and_apply_block(&block);
        assert!(result.is_err(), "should reject block with wrong height");
    }

    /// Produce one real (signed) block on a producer node.
    async fn produce_one_block(producer: &mut NetworkNode) -> Block {
        producer
            .submit_sql("CREATE TABLE t (id BIGINT PRIMARY KEY)")
            .unwrap();
        let mut produced = None;
        for _ in 0..100 {
            if let Some(b) = producer.tick().await {
                produced = Some(b.block);
                break;
            }
        }
        produced.expect("should produce a block")
    }

    /// A block whose proposer signature has been stripped must be rejected.
    #[tokio::test]
    async fn test_verify_rejects_missing_proposer_signature() {
        let mut producer = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();
        let mut block = produce_one_block(&mut producer).await;
        assert!(!block.header.proposer_signature.is_empty());

        block.header.proposer_signature.clear();

        let mut receiver = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();
        let result = receiver.verify_and_apply_block(&block);
        assert!(
            result.is_err(),
            "block without a proposer signature must be rejected"
        );
    }

    /// A block whose header was modified after signing must be rejected.
    #[tokio::test]
    async fn test_verify_rejects_tampered_proposer_signature() {
        let mut producer = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();
        let mut block = produce_one_block(&mut producer).await;

        // Tamper with the state root after the fact — the signature no
        // longer covers the header content.
        block.header.state_root = Hash256::ZERO;

        let mut receiver = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();
        let result = receiver.verify_and_apply_block(&block);
        assert!(
            result.is_err(),
            "block with a header that doesn't match its signature must be rejected"
        );
    }

    /// End-to-end test: producer creates blocks, receiver verifies and applies them.
    /// Both nodes end up with the same state.
    #[tokio::test]
    async fn test_multi_node_sync() {
        // Producer + receiver share a two-validator set so the receiver
        // recognizes the producer as a registered proposer.
        let (mut producer, mut receiver) = start_validator_pair().await;

        // Deploy schema + insert data on producer
        producer
            .submit_sql(
                "CREATE TABLE items (id BIGINT PRIMARY KEY, name TEXT NOT NULL, price BIGINT)",
            )
            .unwrap();
        producer
            .submit_sql("INSERT INTO items (id, name, price) VALUES (1, 'Widget', 100)")
            .unwrap();
        producer
            .submit_sql("INSERT INTO items (id, name, price) VALUES (2, 'Gadget', 250)")
            .unwrap();
        producer
            .submit_sql("INSERT INTO items (id, name, price) VALUES (3, 'Doohickey', 75)")
            .unwrap();

        // Produce blocks on the producer and verify them live on the
        // receiver, ticking the receiver in lockstep so it checks each
        // block at the slot the producer proposed it in (the VRF check
        // uses the receiver's own current slot).
        let mut produced_blocks = Vec::new();
        for _ in 0..200 {
            let block = producer.tick().await;
            receiver.tick().await;
            if let Some(fb) = block {
                produced_blocks.push(fb.block.clone());
                receiver.verify_and_apply_block(&fb.block).unwrap();
                if produced_blocks.len() > 1 {
                    break;
                }
            }
            // Add more data for second block
            if produced_blocks.len() == 1 {
                producer
                    .submit_sql(
                        "INSERT INTO items (id, name, price) VALUES (4, 'Thingamajig', 500)",
                    )
                    .unwrap();
                producer
                    .submit_sql("UPDATE items SET price = 150 WHERE id = 1")
                    .unwrap();
            }
        }
        assert!(
            !produced_blocks.is_empty(),
            "producer should create at least 1 block"
        );

        let producer_height = producer.height();
        let producer_state = *producer.state_root();

        // Both nodes should be at the same state
        assert_eq!(
            receiver.height(),
            producer_height,
            "receiver height should match producer"
        );
        assert_eq!(
            *receiver.state_root(),
            producer_state,
            "receiver state root should match producer"
        );

        // Receiver can query the data
        let result = receiver.query_sql("SELECT * FROM items").unwrap();
        assert!(
            result.rows.len() >= 3,
            "receiver should have the items after sync"
        );

        // Query specific data
        let result = receiver
            .query_sql("SELECT * FROM items WHERE price > 200")
            .unwrap();
        assert!(!result.rows.is_empty(), "should find expensive items");
    }

    /// F3 — the core no-fork regression, SQL variant. A **non-origin**
    /// proposer must stamp a `state_root` that its replayers reproduce.
    ///
    /// The SQL write is authored by a third, off-network identity and gossiped
    /// to the producer, so the producer never executed it itself: its
    /// committed engine lacks the table until the on-block transition runs.
    /// Pre-fix, the producer stamped a root from that (pre-write) store while
    /// the replayer re-executed the write on replay and computed a different
    /// root — `verify_and_apply_block` rejected the block. Post-fix the
    /// producer and every replayer run the same `apply_block_transition`, so
    /// the root is a pure function of (committed pre-state, block) and all
    /// nodes agree. `verify_and_apply_block(...).unwrap()` below is the F3
    /// assertion itself (a mismatched root is an `Err`).
    #[tokio::test]
    async fn test_f3_non_origin_proposer_sql() {
        // Node A is the only active validator (proposes every slot); node B is
        // the inactive receiver that stays slot-synced so its VRF slot matches
        // the proposal slot.
        let (mut producer, mut receiver) = start_validator_pair().await;

        // Author + sign a SQL write as an off-network identity (fresh key),
        // exactly as a peer would before gossiping it.
        let (sk_origin, vk_origin) = SigningKey::generate();
        let sql = "CREATE TABLE gossip (id BIGINT PRIMARY KEY, v TEXT)";
        let payload = sql.as_bytes().to_vec();
        let signature = sk_origin
            .sign(&payload)
            .unwrap()
            .to_bytes()
            .to_vec();
        let tx = Transaction {
            tx_type: seal_storage::block_store::TxType::SqlExec,
            payload,
            sender: vk_origin.to_bytes(),
            signature,
        };

        // Gossip it to the (non-origin) producer. `accept_transaction` enqueues
        // it in the producer's pool without touching the committed engine —
        // the producer's committed store still lacks the table (the fork
        // source, pre-fix).
        producer
            .runner
            .accept_transaction(tx)
            .expect("producer should accept the gossiped SQL write");

        // The producer proposes a block containing the gossiped write; the
        // receiver ticks in lockstep so its slot matches the proposal slot.
        let mut block = None;
        for _ in 0..100 {
            receiver.tick().await;
            if let Some(b) = producer.tick().await {
                block = Some(b);
                break;
            }
        }
        let block = block
            .expect("producer should propose a block with the gossiped tx");

        // The gossiped write must be in the block the producer proposed.
        assert!(
            block
                .block
                .transactions
                .iter()
                .any(|t| t.tx_type == seal_storage::block_store::TxType::SqlExec),
            "block should contain the gossiped SQL write"
        );

        // THE F3 assertion: the receiver (replayer) must reproduce the
        // producer's stamped state_root. Pre-fix this returned `Err` (root
        // mismatch); post-fix the shared transition makes the root a pure
        // function of (committed pre-state, block).
        receiver
            .verify_and_apply_block(&block.block)
            .expect("replayer must reproduce the non-origin proposer's state root (F3)");

        assert_eq!(
            *producer.state_root(),
            *receiver.state_root(),
            "non-origin proposer's state root must equal every replayer's (F3)"
        );
        assert_eq!(
            producer.height(),
            receiver.height(),
            "producer and receiver heights should match"
        );

        // The receiver can query the gossiped table (proving the write landed
        // on the replayer's committed state, not just the producer's).
        let result = receiver.query_sql("SELECT * FROM gossip").unwrap();
        assert_eq!(result.rows.len(), 0, "CREATE TABLE only: no rows yet");
    }

    /// T1 (DEX forgeability, relayer vector): a peer who takes a validly-signed
    /// block and injects a fabricated `DexMatch` transaction — no re-sign needed,
    /// since neither the header signature nor `state_root` covers
    /// `transactions` — must be stopped. Pre-`tx_root` the injected no-op
    /// committed (it affects no root); the signed `tx_root` makes the
    /// transaction set tamper-evident, so the recomputed root differs and the
    /// block is rejected. (Design: audits/2026-10-08-dexmatch-txroot-design.md.)
    #[tokio::test]
    async fn test_dexmatch_injected_tx_rejected_on_replay() {
        use seal_token::orderbook::{OrderType, Side, Trade};

        let (mut producer, mut receiver) = start_validator_pair().await;

        // Pre-load crossing orders so the producer emits a real DexMatch.
        {
            let mut dex = producer
                .runner
                .dex
                .try_lock()
                .expect("uncontended lock at setup");
            dex.create_pair("FAKE".into(), "SEAL".into()).unwrap();
            let book = dex.get_book_mut("FAKE/SEAL").unwrap();
            // Bid 100 / ask 90 cross; matched at block time at the ask price.
            book.place_order("attacker".into(), Side::Bid, 100, 1, OrderType::Limit, 0);
            book.place_order("attacker".into(), Side::Ask, 90, 1, OrderType::Limit, 0);
        }

        // Produce a block carrying a real DexMatch, ticking the receiver in
        // lockstep so its VRF slot matches the proposal slot.
        let mut finalized = None;
        for _ in 0..100 {
            receiver.tick().await;
            if let Some(b) = producer.tick().await {
                finalized = Some(b);
                break;
            }
        }
        let finalized =
            finalized.expect("producer should propose a block within 100 slots");
        assert!(
            finalized
                .block
                .transactions
                .iter()
                .any(|t| t.tx_type == seal_storage::block_store::TxType::DexMatch),
            "block must carry a real DexMatch before we tamper with it"
        );

        // FORGE (T1): a third party appends a fabricated DexMatch to a copy of
        // the validly-signed block. The header (and its `tx_root` + signature)
        // is untouched.
        let mut forged = finalized.block.clone();
        let fake: Vec<(String, Vec<Trade>)> = vec![(
            "FAKE/SEAL".to_string(),
            vec![Trade {
                id: 9_999_999,
                maker_order_id: 1,
                taker_order_id: 2,
                price: 1,
                quantity: 1_000_000,
                maker: "attacker".into(),
                taker: "victim".into(),
                side: Side::Bid,
                timestamp: 0,
            }],
        )];
        forged.transactions.push(Transaction {
            tx_type: seal_storage::block_store::TxType::DexMatch,
            payload: bincode::serialize(&fake).expect("serialize forged payload"),
            sender: forged.header.proposer.clone(),
            signature: Vec::new(),
        });

        // The receiver must reject the tampered block and stay put.
        let result = receiver.verify_and_apply_block(&forged);
        assert!(
            result.is_err(),
            "a validly-signed block with an injected DexMatch must be rejected: {:?}",
            result
        );
        assert_eq!(
            receiver.height(),
            0,
            "a forged block must not advance the receiver"
        );
    }

    /// F3 — native money transfer variant. A non-origin proposer must stamp a
    /// `state_root` that reproduces the movement its replayers apply on replay.
    ///
    /// The transfer is authored off-network and gossiped to the producer, so
    /// the producer's committed ledger has NOT applied the debit/credit (the
    /// pre-fix fork source). Post-fix the shared on-block transition moves the
    /// balance identically on the producer and every replayer, so their roots
    /// agree — and both ledgers reflect the movement.
    #[tokio::test]
    async fn test_f3_non_origin_proposer_transfer() {
        let (mut producer, mut receiver) = start_validator_pair().await;

        // Fund the sender on BOTH nodes: both run the same transition, so both
        // need `from` solvent for the movement to apply (a failing transfer
        // aborts the whole transition).
        let from = "seal1f3sender";
        let to = "seal1f3recv";
        let amount = 100u64;
        producer
            .runner
            .balances
            .mint(from, 1_000)
            .expect("fund sender on producer");
        receiver
            .runner
            .balances
            .mint(from, 1_000)
            .expect("fund sender on receiver");

        // Author + sign a Transfer as an off-network identity (fresh key).
        let (sk_origin, vk_origin) = SigningKey::generate();
        let body = crate::consensus_runner::MoneyPayload {
            from: from.into(),
            to: to.into(),
            amount,
        };
        let payload =
            crate::consensus_runner::encode_money_payload(0, &body).expect("encode transfer");
        let signature = sk_origin.sign(&payload).unwrap().to_bytes().to_vec();
        let tx = Transaction {
            tx_type: seal_storage::block_store::TxType::Transfer,
            payload,
            sender: vk_origin.to_bytes(),
            signature,
        };

        // Gossip to the (non-origin) producer: enqueued, not yet applied.
        producer
            .runner
            .accept_transaction(tx)
            .expect("producer should accept the gossiped transfer");

        let mut block = None;
        for _ in 0..100 {
            receiver.tick().await;
            if let Some(b) = producer.tick().await {
                block = Some(b);
                break;
            }
        }
        let block = block.expect("producer should propose a block with the gossiped transfer");

        assert!(
            block
                .block
                .transactions
                .iter()
                .any(|t| t.tx_type == seal_storage::block_store::TxType::Transfer),
            "block should contain the gossiped transfer"
        );

        // THE F3 assertion: the replayer reproduces the producer's root.
        receiver
            .verify_and_apply_block(&block.block)
            .expect("replayer must reproduce the non-origin proposer's state root (F3)");
        assert_eq!(
            *producer.state_root(),
            *receiver.state_root(),
            "non-origin proposer's state root must equal every replayer's (F3)"
        );

        // Both ledgers reflect the movement identically (the fee is charged to
        // the sender's vk-derived address, not `from`, so `from`/`to` see only
        // the transfer).
        assert_eq!(producer.runner.balances.available(from), 1_000 - amount);
        assert_eq!(receiver.runner.balances.available(from), 1_000 - amount);
        assert_eq!(producer.runner.balances.available(to), amount);
        assert_eq!(receiver.runner.balances.available(to), amount);
    }

    /// F3 — funded SQL write: per-byte storage burn + per-tx fee applied
    /// identically on the producer and every replayer.
    ///
    /// Pre-fix these balance effects were produce-only, so a funded block's
    /// replayer ledger diverged from the proposer's. Post-fix the shared
    /// transition charges both from the same (committed pre-state, block), so
    /// the sender loses the same amount on every node and the roots agree.
    #[tokio::test]
    async fn test_f3_funded_sql_fee_storage() {
        let (mut producer, mut receiver) = start_validator_pair().await;

        // The write's sender is billed the storage burn + fee off its
        // vk-derived address. Fund that address on both nodes so the burns
        // actually apply (an unfunded sender burns nothing, hiding the
        // produce/replay drift) and the divergence is observable.
        let (sk_origin, vk_origin) = SigningKey::generate();
        let sender_addr = hex::encode(&vk_origin.to_bytes()[..16]);
        producer
            .runner
            .balances
            .mint(&sender_addr, 100_000)
            .expect("fund sender on producer");
        receiver
            .runner
            .balances
            .mint(&sender_addr, 100_000)
            .expect("fund sender on receiver");

        let sql = "CREATE TABLE charged (id BIGINT PRIMARY KEY, v TEXT)";
        let payload = sql.as_bytes().to_vec();
        let signature = sk_origin.sign(&payload).unwrap().to_bytes().to_vec();
        let tx = Transaction {
            tx_type: seal_storage::block_store::TxType::SqlExec,
            payload,
            sender: vk_origin.to_bytes(),
            signature,
        };
        producer
            .runner
            .accept_transaction(tx)
            .expect("accept the gossiped SQL write");

        let mut block = None;
        for _ in 0..100 {
            receiver.tick().await;
            if let Some(b) = producer.tick().await {
                block = Some(b);
                break;
            }
        }
        let block = block.expect("producer should propose a block with the gossiped tx");

        receiver
            .verify_and_apply_block(&block.block)
            .expect("replayer must reproduce the producer's root (F3 fee/storage)");
        assert_eq!(
            *producer.state_root(),
            *receiver.state_root(),
            "non-origin proposer's state root must equal every replayer's (F3 fee/storage)"
        );

        // The storage burn (>= 1 micro-SEAL per written byte) was charged to
        // the funded sender, identically on producer and replayer.
        let burned_producer = 100_000 - producer.runner.balances.available(&sender_addr);
        let burned_receiver = 100_000 - receiver.runner.balances.available(&sender_addr);
        assert!(
            burned_producer > 0,
            "storage burn should have charged the funded sender"
        );
        assert_eq!(
            burned_producer, burned_receiver,
            "storage/fee burn must match on producer and replayer (F3)"
        );
    }

    /// Test: produce multiple blocks, sync, then produce more on receiver.
    #[tokio::test]
    async fn test_sync_then_continue() {
        let (mut producer, mut receiver) = start_validator_pair().await;

        producer
            .submit_sql("CREATE TABLE counter (id BIGINT PRIMARY KEY, val BIGINT)")
            .unwrap();
        producer
            .submit_sql("INSERT INTO counter (id, val) VALUES (1, 0)")
            .unwrap();

        // Produce the first block, keeping the receiver slot-synced so it
        // can verify at the block's proposal slot.
        let mut blocks = Vec::new();
        for _ in 0..100 {
            let block = producer.tick().await;
            receiver.tick().await;
            if let Some(fb) = block {
                blocks.push(fb.block.clone());
                break;
            }
        }
        assert_eq!(blocks.len(), 1);

        // Sync to receiver
        for block in &blocks {
            receiver.verify_and_apply_block(block).unwrap();
        }

        // Receiver can now continue independently
        receiver
            .submit_sql("UPDATE counter SET val = 42 WHERE id = 1")
            .unwrap();
        let result = receiver
            .query_sql("SELECT * FROM counter WHERE id = 1")
            .unwrap();
        assert_eq!(result.rows.len(), 1);
    }

    #[tokio::test]
    async fn test_sync_blocks() {
        let (mut producer, mut joiner) = start_validator_pair().await;

        producer
            .submit_sql("CREATE TABLE data (id BIGINT PRIMARY KEY, val TEXT)")
            .unwrap();
        producer
            .submit_sql("INSERT INTO data (id, val) VALUES (1, 'first')")
            .unwrap();

        // Produce 3 blocks
        let mut block_count = 0;
        for _ in 0..200 {
            producer
                .submit_sql(&format!(
                    "INSERT INTO data (id, val) VALUES ({}, 'row')",
                    10 + block_count
                ))
                .unwrap();
            if producer.tick().await.is_some() {
                block_count += 1;
                if block_count >= 3 {
                    break;
                }
            }
        }
        assert!(block_count >= 2);

        let chain = producer.get_chain();

        assert!(joiner.is_behind(producer.height()));
        assert_eq!(joiner.blocks_behind(producer.height()), producer.height());

        // Catch up the way the live receive path does (step the joiner to
        // each block's slot, then verify + apply).
        let applied = apply_chain_live(&mut joiner, &chain).await;
        assert!(applied >= 2);
        assert_eq!(joiner.height(), producer.height());
        assert!(!joiner.is_behind(producer.height()));

        // Data is available
        let result = joiner.query_sql("SELECT * FROM data").unwrap();
        assert!(result.rows.len() >= 2);
    }

    #[tokio::test]
    async fn test_sync_skips_existing_blocks() {
        let (mut producer, mut receiver) = start_validator_pair().await;
        producer
            .submit_sql("CREATE TABLE t (id BIGINT PRIMARY KEY)")
            .unwrap();

        for _ in 0..100 {
            if producer.tick().await.is_some() {
                break;
            }
        }
        let chain = producer.get_chain();
        assert!(!chain.is_empty());

        // First sync: catch up live (step the receiver to each block's slot,
        // then verify + apply).
        let applied1 = apply_chain_live(&mut receiver, &chain).await;
        assert!(applied1 > 0);

        // Second sync with the same blocks — every height is already at or
        // behind the receiver's tip, so `sync_blocks` skips them all before
        // ever reaching verification.
        let applied2 = receiver.sync_blocks(&chain).unwrap();
        assert_eq!(applied2, 0, "should skip already-applied blocks");
    }

    #[tokio::test]
    async fn handle_bridge_ringtail_round1_silent_without_orchestrator() {
        // Default-feature default-construction path: the receive arm
        // logs at debug + drops. Calling the handler with garbage
        // bytes must NOT panic or error visibly when no orchestrator
        // is attached — that's the HMAC committee-of-1 production
        // baseline (operators running without the multi-validator
        // PQ flag set should pay zero cost on Ringtail traffic
        // observed from the wire).
        let node = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();
        let peer = libp2p::PeerId::random();
        node.handle_bridge_ringtail_round1(b"not valid json".to_vec(), peer)
            .await;
        node.handle_bridge_ringtail_round2(b"not valid json".to_vec(), peer)
            .await;
        node.handle_bridge_ringtail_aggregate(b"not valid json".to_vec(), peer)
            .await;
    }

    #[cfg(feature = "ringtail-singleton")]
    #[tokio::test]
    async fn handle_bridge_ringtail_aggregate_attaches_signature_to_bridge() {
        use seal_bridge::ringtail::BridgeRingtailAggregateEnvelope;
        use seal_bridge::types::Chain;
        use seal_bridge::{BridgeDeposit, BridgeManager, WrappedToken};
        use std::sync::Arc;
        use tokio::sync::Mutex as TokioMutex;

        // Build a BridgeManager with a pending withdrawal whose
        // committee_signature is still unset, mirroring the
        // multi-validator flow before the aggregate lands.
        let mut bridge = BridgeManager::new(1);
        bridge
            .observe_deposit(BridgeDeposit {
                id: "dep_fixture".into(),
                source_chain: Chain::Solana,
                source_address: "src".into(),
                source_tx_hash: "tx".into(),
                seal_address: "seal1alice".into(),
                amount: 1000,
                token: WrappedToken::WSOL,
                confirmations: 1,
                processed: false,
            })
            .expect("observe deposit");
        bridge
            .process_deposit("dep_fixture")
            .expect("process deposit");
        let wd_id = bridge
            .initiate_withdrawal(
                "seal1alice",
                Chain::Solana,
                "11111111111111111111111111111111",
                WrappedToken::WSOL,
                500,
            )
            .expect("burn withdrawal");
        assert!(bridge
            .get_withdrawal(&wd_id)
            .and_then(|w| w.committee_signature_hex.clone())
            .is_none(),);

        // Boot a NetworkNode and attach the bridge.
        let mut node = NetworkNode::start(ConsensusConfig::default(), NodeConfig::default())
            .await
            .unwrap();
        let bridge_arc = Arc::new(TokioMutex::new(bridge));
        node.attach_bridge(Arc::clone(&bridge_arc));

        // Simulate a peer broadcasting an aggregate envelope for our
        // withdrawal (race-loser path — we never started signing
        // locally).
        let env = BridgeRingtailAggregateEnvelope {
            withdrawal_id: wd_id.clone(),
            dest_chain: Chain::Solana,
            signature_hex: "0123456789abcdef".repeat(261), // dummy
        };
        let bytes = serde_json::to_vec(&env).unwrap();
        let peer = libp2p::PeerId::random();
        node.handle_bridge_ringtail_aggregate(bytes, peer).await;

        let attached = bridge_arc
            .lock()
            .await
            .get_withdrawal(&wd_id)
            .and_then(|w| w.committee_signature_hex.clone());
        assert_eq!(
            attached,
            Some(env.signature_hex),
            "Aggregate envelope must land on BridgeManager via attach_committee_signature",
        );
    }
}
