#!/usr/bin/env bash
# scripts/bridge-deploy-devnet.sh — public devnet/testnet deploy of
# the Solana Anchor + Stellar Soroban bridge programs, plus the
# matching seal_addBridgeObserver registration on a running
# seal-node.
#
# Closes P4 of the testnet-readiness checklist: "operator runs
# anchor deploy + stellar contract deploy + seal_addBridgeObserver
# for both chains". Replaces 6+ manual steps with one shell
# invocation that captures the IDs and prints them back in env-var
# form for the operator to paste into systemd / docker-compose.
#
# Usage:
#   ./scripts/bridge-deploy-devnet.sh \
#       --solana-keypair $HOME/.config/solana/id.json \
#       --stellar-account G... \
#       --seal-rpc http://127.0.0.1:8645
#
# Required:
#   --solana-keypair <path>   Funded Solana devnet keypair (use
#                             `solana airdrop 2 <pubkey> --url devnet`
#                             via scripts/bridge-faucet.sh sol).
#   --stellar-account <G..>   Funded Stellar testnet account (use
#                             scripts/bridge-faucet.sh xlm <G..>).
#   --seal-rpc <url>          Where to call seal_addBridgeObserver.
#                             Defaults to http://127.0.0.1:8645
#                             (bridge stack — validator stack uses
#                             8545; override if you mean that one).
#
# Optional:
#   --skip-solana             Only deploy the Stellar side.
#   --skip-stellar            Only deploy the Solana side.
#   --skip-observer           Just deploy; don't call addBridgeObserver.
#   --features ringtail-verify  Build with the PQ-verify feature on
#                             (mirrors bridge-redeploy-ringtail.sh).
#
# Outputs:
#   bridges/.deploy-devnet.env   sourceable env file with
#                                SEAL_BRIDGE_SOL_PROGRAM_ID +
#                                SEAL_BRIDGE_XLM_CONTRACT_ID.

set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
say() { echo -e "${BOLD}==>${NC} $*"; }
ok()  { echo -e "${GREEN}✓${NC} $*"; }
warn(){ echo -e "${YELLOW}!${NC} $*"; }
err() { echo -e "${RED}✗${NC} $*" >&2; }

SOLANA_KEYPAIR=""
STELLAR_ACCOUNT=""
SEAL_RPC="http://127.0.0.1:8645"
SKIP_SOLANA=0
SKIP_STELLAR=0
SKIP_OBSERVER=0
EXTRA_FEATURES=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --solana-keypair) SOLANA_KEYPAIR="$2"; shift 2 ;;
        --stellar-account) STELLAR_ACCOUNT="$2"; shift 2 ;;
        --seal-rpc) SEAL_RPC="$2"; shift 2 ;;
        --skip-solana) SKIP_SOLANA=1; shift ;;
        --skip-stellar) SKIP_STELLAR=1; shift ;;
        --skip-observer) SKIP_OBSERVER=1; shift ;;
        --features) EXTRA_FEATURES="$2"; shift 2 ;;
        *) err "unknown arg: $1"; exit 1 ;;
    esac
done

if [[ $SKIP_SOLANA -eq 0 && -z "$SOLANA_KEYPAIR" ]]; then
    err "--solana-keypair required (or pass --skip-solana)"
    exit 1
fi
if [[ $SKIP_STELLAR -eq 0 && -z "$STELLAR_ACCOUNT" ]]; then
    err "--stellar-account required (or pass --skip-stellar)"
    exit 1
fi

# Make sure the workspace vendor config doesn't poison anchor/soroban
# crates.io lookups (same dance as scripts/bridge-test-ringtail.sh).
VENDOR_CFG=".cargo/config.toml"
VENDOR_CFG_BAK=".cargo/config.toml.deploy-devnet-bak"
restore_vendor_cfg() {
    if [[ -f "$VENDOR_CFG_BAK" ]]; then
        mv "$VENDOR_CFG_BAK" "$VENDOR_CFG"
        ok "restored $VENDOR_CFG"
    fi
}
trap restore_vendor_cfg EXIT
if [[ -f "$VENDOR_CFG" ]]; then
    mv "$VENDOR_CFG" "$VENDOR_CFG_BAK"
    ok "moved $VENDOR_CFG aside (vendor-sources config blocks anchor/soroban deps)"
fi

OUT_ENV="bridges/.deploy-devnet.env"
: > "$OUT_ENV"
echo "# auto-generated by scripts/bridge-deploy-devnet.sh on $(date -u +%FT%TZ)" >> "$OUT_ENV"

SOL_PROGRAM_ID=""
XLM_CONTRACT_ID=""

# ── Solana deploy ─────────────────────────────────────────────
if [[ $SKIP_SOLANA -eq 0 ]]; then
    say "Solana: anchor build${EXTRA_FEATURES:+ (--features $EXTRA_FEATURES)} + anchor deploy --provider.cluster devnet"
    pushd bridges/solana >/dev/null
    if [[ -n "$EXTRA_FEATURES" ]]; then
        anchor build --features "$EXTRA_FEATURES"
    else
        anchor build
    fi
    # `anchor deploy --provider.cluster devnet` uses the Solana CLI's
    # active config for the payer; pin to the supplied keypair via
    # ANCHOR_WALLET so this script is idempotent across operator
    # machines that haven't run `solana config set --keypair`.
    ANCHOR_WALLET="$SOLANA_KEYPAIR" anchor deploy --provider.cluster devnet 2>&1 | tee /tmp/seal-bridge-deploy-sol.log
    # Grab the program-id Anchor logged.
    SOL_PROGRAM_ID=$(grep -oE 'Program Id: [A-Za-z0-9]+' /tmp/seal-bridge-deploy-sol.log | head -1 | awk '{print $3}')
    if [[ -z "$SOL_PROGRAM_ID" ]]; then
        # Fallback: extract from the IDL file Anchor wrote.
        SOL_PROGRAM_ID=$(jq -r '.address // .metadata.address // empty' target/idl/seal_bridge.json 2>/dev/null || true)
    fi
    if [[ -z "$SOL_PROGRAM_ID" ]]; then
        err "could not infer Solana program id from anchor deploy output"
        popd >/dev/null
        exit 2
    fi
    ok "Solana program deployed: $SOL_PROGRAM_ID"
    echo "SEAL_BRIDGE_SOL_PROGRAM_ID=$SOL_PROGRAM_ID" >> "$REPO_ROOT/$OUT_ENV"
    popd >/dev/null
fi

# ── Stellar deploy ────────────────────────────────────────────
if [[ $SKIP_STELLAR -eq 0 ]]; then
    say "Stellar: stellar contract build${EXTRA_FEATURES:+ (--features $EXTRA_FEATURES)} + stellar contract deploy --network testnet"
    pushd bridges/stellar >/dev/null
    if [[ -n "$EXTRA_FEATURES" ]]; then
        cargo build --target wasm32v1-none --release --features "$EXTRA_FEATURES"
    else
        stellar contract build
    fi
    XLM_CONTRACT_ID=$(stellar contract deploy \
        --wasm target/wasm32v1-none/release/seal_bridge_stellar.wasm \
        --network testnet \
        --source "$STELLAR_ACCOUNT")
    if [[ -z "$XLM_CONTRACT_ID" ]]; then
        err "stellar contract deploy returned no contract-id"
        popd >/dev/null
        exit 2
    fi
    ok "Stellar contract deployed: $XLM_CONTRACT_ID"
    echo "SEAL_BRIDGE_XLM_CONTRACT_ID=$XLM_CONTRACT_ID" >> "$REPO_ROOT/$OUT_ENV"
    popd >/dev/null
fi

# ── seal_addBridgeObserver ────────────────────────────────────
if [[ $SKIP_OBSERVER -eq 0 ]]; then
    if [[ -n "$SOL_PROGRAM_ID" ]]; then
        say "seal_addBridgeObserver for Solana on $SEAL_RPC"
        curl --silent --fail -X POST "$SEAL_RPC" \
            -H 'content-type: application/json' \
            -d "$(cat <<JSON
{"jsonrpc":"2.0","id":1,"method":"seal_addBridgeObserver","params":{
  "chain": "Solana",
  "rpc_url": "https://api.devnet.solana.com",
  "program_id": "$SOL_PROGRAM_ID",
  "poll_interval_secs": 10
}}
JSON
)" | tee /tmp/seal-bridge-observer-sol.log
        echo
        ok "registered Solana observer"
    fi
    if [[ -n "$XLM_CONTRACT_ID" ]]; then
        say "seal_addBridgeObserver for Stellar on $SEAL_RPC"
        curl --silent --fail -X POST "$SEAL_RPC" \
            -H 'content-type: application/json' \
            -d "$(cat <<JSON
{"jsonrpc":"2.0","id":1,"method":"seal_addBridgeObserver","params":{
  "chain": "Stellar",
  "horizon_url": "https://horizon-testnet.stellar.org",
  "contract_id": "$XLM_CONTRACT_ID",
  "poll_interval_secs": 10
}}
JSON
)" | tee /tmp/seal-bridge-observer-xlm.log
        echo
        ok "registered Stellar observer"
    fi
fi

echo
ok "deploy complete. Env vars written to $OUT_ENV:"
cat "$OUT_ENV"
echo
say "Paste into your systemd unit / docker-compose env, then restart seal-node."
